---@class Tile
---@field x integer
---@field y integer
---@field fg integer
---@field bg integer
---@field flag integer
---@field readyharvest boolean
---@field extra TileExtra
---@field collidable boolean
---@field coltype integer
---@field progress integer
local Tile = {}
