---Make a GL dialog.
---
---Example:
---```lua
---sendDialog({title = "Dialog test", message = "Hello World", confirm = "Ok", url = "discord.com", alias = "D"})
---```
---@param title string
---@param message string
---@param confirm string
---@param url string
---@param alias string
function sendDialog(title, message, confirm, url, alias) end
